name: Instalar Node.js y comprobar versi贸n
description: Esta acci贸n instala Node.js en el runner de GitHub Actions y comprueba la versi贸n instalada

on: [push]

jobs:
 install-node:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Instalar Node.js
     run: |
       curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo apt-get install -y nodejs

   - name: Comprobar versi贸n de Node.js
     run: node -v
